import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/provider/providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My first Redux-App",
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <Providers><body className={inter.className}>{children}</body></Providers> 
    </html>
  );
}
